apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  namespace: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      env: blue
  template:
    metadata:
      labels:
        app: my-app
        env: blue
    spec:
      containers:
        - name: my-app
          image: myregistry.azurecr.io/my-app:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "blue"
