apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      env: green
  template:
    metadata:
      labels:
        app: my-app
        env: green
    spec:
      containers:
        - name: my-app
          image: myregistry.azurecr.io/my-app:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "green"

